module.exports = {
    unauthorized: "unauthorized",
    invalidtoken: "invalid token",
    internalServerError: "internal Server Error",
    success: "success",
    Invalid_Role:"Invalid Role",
    tokenMissing: "authorization header missing or invalid",
    fetch_products:"An error occurred while fetching products.",
    fetch_orders:"An error occurred while fetching orders.",
    Unable_To_fetch_users:"An error occurred while fetching users.",
    Unable_To_fetch_items:"An error occurred while fetching items.",
    Unable_To_Update_users:"An error occurred while updating users.",
    Unable_To_Update_Items:"An error occurred while updating items.",
    Unable_To_Fetch_Orders:"An error occurred while fetching orders.",
    Unable_To_Delete_Orders:"An error occurred while deleting orders.",
    Unable_To_Delete_Products:"An error occurred while deleting products.",
    Unable_To_Fetch_MasterData:"An error occurred while fetching masterData.",
    Not_Found:"Not Found",
    false:false,
    true:true,
    Correct_Page_Limit:"provide correct page and limit",
    Successfully_deleted:"Order deleted successfully",
    Product_deleted:"Product deleted successfully",
    Unable_To_Swap_Categories:"Unable_To_Swap_Categories",
    User_Already_Exists:"User_Already_Exists",
    Invalid_email:"Invalid email",
    Invalid_password:"Invalid  password",
    BadRequest:"BadRequest",
    exists:"already_Exits",
    Position_Not_Found:"Position_Not_Found"
}